title: JAC
author: Jovanni A. Cutigni
# description: All content copyright Jovanni A. Cutigni &#169; 2019 &#8226; All rights reserved.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: ContextLostRBX
github_username:  jovannic
minima:
  social_links: 
    twitter: ContextLostRBX
    github:  jovannic
    linkedin: jcutigni

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
